server:
  port: 7003

spring:
  application:
    name: zzz

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://20.26.28.167:8988/eureka/
  instance:
    instance-id: zzz   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址


#zuul:
#  routes:
#    client-a:
#      path: /client/**
#      serviceId: zzz